export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_CONFIRM = 'SET_CONFIRM';
export const SET_CONFIRM_TYPE = 'SET_CONFIRM_TYPE';
export const SET_CONFIRM_DELETE_ID = 'SET_CONFIRM_DELETE_ID';
export const SET_CONFIRM_DATA = 'SET_CONFIRM_DATA';
